export { default as HeroSection } from './HeroSection'
export { default as Brands } from './Brands'
export { default as Sidebar } from './Sidebar'
export { default as Footer } from './Footer'
export { default as WhoWeAre } from './WhoWeAre'
